# Checkout caddy from github into /app/caddy
FROM alpine/git AS gitCaddy
RUN mkdir /app
WORKDIR /app/
RUN git clone https://github.com/caddyserver/caddy.git /app/caddy
RUN ls -ltr

FROM ubuntu AS goBuild
WORKDIR /go/
COPY --from=0 /app ./
ENTRYPOINT ["/app/caddy/cmd/caddy/go build"]

FROM ubuntu as ubuntu
WORKDIR /app/
COPY --from=0 /app ./
ENTRYPOINT ["/app/caddy/cmd/caddy/go build"]
